#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso src/boundaryConditions/FO_BC
wclean libso src/boundaryConditions/RO_BC

wclean src/solvers/pisoSaltTransport
wclean src/solvers/potentialSalt
wclean src/solvers/simpleSaltTransport

wclean src/utilities/sampleMembrane

# ----------------------------------------------------------------- end-of-file
