#!/bin/sh
set -eu
cd "$(dirname "$0")"
: "${WM_PROJECT_DIR:?Source OpenFOAM before cleaning}"
wclean libso src/boundaryConditions
for solver in pisoSaltTransport potentialSalt simpleSaltTransport simpleSaltDiffusion; do
    wclean "src/solvers/$solver"
done
