#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso src/boundaryConditions

#wmake src/solvers/pisoSaltTransport
wmake src/solvers/potentialSalt
wmake src/solvers/simpleSaltTransport
#wmake src/solvers/simpleSaltDiffusion
#wmake src/solvers/simplePorousSaltTransport

#wmake src/porosityModels



# ----------------------------------------------------------------- end-of-file
