#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso src/boundaryConditions

wmake src/solvers/pisoSaltTransport
wmake src/solvers/potentialSalt
wmake src/solvers/simpleSaltTransport
wmake src/solvers/simpleSaltDiffusion

# Experimental work
# wmake src/solvers/simplePorousSaltTransport

# Experimental work
# wmake src/porosityModels

# Temporary utility used for experimental project
# wmake src/utilities/sampleMembrane

# ----------------------------------------------------------------- end-of-file
